name: Build Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ ubuntu-20.04, macos-11 ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Stop Gradle
        run: ./gradlew --stop

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifacts
          path: build/libs/
